### ISSUE TITLE
wrong calculation of info gain function 

### ISSUE THREAD

**Issue by surajrautela** [jabbermonkey/dtree_bias_var#1]
The code used in the info gain function is wrong it should be entropy(labels)-(EA/total_sum)

**Comment by paulc00** [comment]
Thanks @surajrautela. I've updated to subtract from entropy for labels (i.e. the global entropy) as you suggested. 

The weighting used for each attribute value's entropy within the attribute entropy calculation loop is attr_val_count / total_count. I just pushed the division of the total outside of the sum loop to improve performance. Based on this it doesn't look like total_count needs to be replaced with a total_sum.
